import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="pageContainer">
          <header className="mainHeader">
            <h1>Calcolo netto annuale</h1>
            <p>
              Inserisci una retribuzione lorda per calcolare il reddito netto.
            </p>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
